name: Health check

on:
  schedule:
    - cron: 0 0/6 * * *
  repository_dispatch:
    types: [health_check]

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - uses: jurassiscripts/setup-velociraptor@v1
      - run: VR_HOOKS=false vr health_check
